apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: thinknyx/result:1.0
        name: result
